import type { Metadata } from 'next'
import './globals.css'

import { Inter } from 'next/font/google'

import cn from '@/utils/cn'
import { UserProvider } from '@auth0/nextjs-auth0/client'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <UserProvider>
                <body
                    className={cn(
                        inter.className,
                        'bg-neutral-100 dark:bg-neutral-950'
                    )}
                >
                    {children}
                </body>
            </UserProvider>
        </html>
    )
}
